spring:
  application:
    name: User Manager
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    generate-ddl: false
  liquibase:
    change-log: liquibase/master.xml

logging:
  level:
    liquibase: info

server:
  port: 8080