spring:
  application:
    name: User Manager
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:user_manager_database
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    generate-ddl: false
  liquibase:
    change-log: liquibase/master.xml

logging:
  level:
    fr.orionbs.user_manager: debug
    liquibase: info

server:
  port: 9000